version: "3.8"

services:
  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
