-- init/01_init.sql
CREATE USER 'user'@'%' IDENTIFIED BY '2363alsgud@#';
CREATE DATABASE mysql;
GRANT ALL PRIVILEGES ON DATABASE mysql TO user;
GRANT ALL PRIVILEGES ON mysql.* TO 'user'@'%';
FLUSH PRIVILEGES;